<a href="https://colab.research.google.com/github/paramita-pp/time-series-analysis/blob/main/Maven_Turning_Bullish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Turning Bullish

Source: https://raw.githubusercontent.com/paramita-pp/time-series-analysis/refs/heads/main/Files/SPY_close_price_5Y.csv

Task:
- To calculate 50-day and 20-day moving averages based on the closing price
- Identify every "Golden Corss" moment - when the short-term average (50-day) crosses from below to above long-term average (200-day)

In [1]:
# import library
import pandas as pd

In [2]:
# import data
spy_df = pd.read_csv('https://raw.githubusercontent.com/paramita-pp/time-series-analysis/refs/heads/main/Files/SPY_close_price_5Y.csv', parse_dates  = ['Date'])

spy_df.head()

        Date   Close
0 2020-11-02  330.20
1 2020-11-03  336.03
2 2020-11-04  343.54
3 2020-11-05  350.24
4 2020-11-06  350.16

In [6]:
spy_df.assign(
    ma_50 = lambda d: d.Close.rolling(window = 50, min_periods = 50).mean(), # moving average 50 days
    ma_200 = lambda d: d.Close.rolling(window = 200, min_periods = 200).mean(), # moving average 200 days
    gc = lambda d: ((d.ma_50 > d.ma_200) & (d.ma_50.shift(1) < d.ma_200.shift(1))).astype(int) # golden cross check
).query("gc==1") # query only golden cross

           Date   Close     ma_50     ma_200  gc
566  2023-02-02  416.78  394.3504  394.25025   1
1169 2025-07-01  617.65  583.0978  582.04155   1